// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "LlmSwift",
    platforms: [
        .iOS("18.1")
    ],
    products: [
        .iOSApplication(
            name: "LlmSwift",
            targets: ["AppModule"],
            bundleIdentifier: "com.otabuzzman.llmswift.ios",
            teamIdentifier: "28FV44657B",
            displayVersion: "1.2.0",
            bundleVersion: "29",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.yellow),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/otabuzzman/llm.swift.git", "1.2.11"..<"2.0.0"),
        .package(url: "https://github.com/otabuzzman/CircularBuffer.git", "1.0.1"..<"2.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "LlmDotSwift", package: "llm.swift"),
                .product(name: "CircularBuffer", package: "CircularBuffer")
            ],
            path: ".",
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)
